#fos_elastica:
#    clients:
 #       default:
  #          host: '%fos_elastica.host%'
   #         port: '%fos_elastica.port%'
    #indexes:
     #   search:
      #      finder: ~
       #     client: default
        #    types:
         #       usuarios:
          #          mappings:
           #             id:
            #                type: integer
             #           nombre: ~
              #          rutaFoto: ~
               #     persistence:
                #        driver: orm
                 #       model: App\Entity\Autor
                  #      finder: ~
                   #     provider: ~
                    #    listener: ~