framework:
    secret: '%env(APP_SECRET)%'
    default_locale: es
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    assets:
        packages:
            template:
                base_path: /assets/template
            codice:
                base_path: /assets/codice
            pages:
                base_path: /assets/codice/css/page

    #esi: true
    #fragments: true
    php_errors:
        log: true
