security:
    encoders:
        App\Entity\Autor: { algorithm: bcrypt , cost: 13 }
        App\Entity\Usuario: { algorithm: bcrypt , cost: 13 }

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_DIRECTIVO, ROLE_GESTORBALANCE]
        ROLE_DIRECTIVO:  ROLE_USER

    providers:
        chain_provider:
            chain:
                providers: [autores, usuarios]
        autores:
            entity: { class: App:Autor}
        usuarios:
            entity: { class: App:Usuario}


    firewalls:
        api_area:
            pattern:    ^/api/*
            anonymous: ~
            provider: autores
            guard:
                authenticators:
                    - App\Security\ApiTokenAuthenticator
        secured_area:
            pattern:    ^/*
            provider: chain_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: index
                check_path: check
                default_target_path: index
                always_use_default_target_path: true
            logout:
                path:   logout
                target: index
                handlers: [app.logoutlistener]
            anonymous: ~
            remember_me:
                secret:  '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path: index

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #permisos del superadmin
        - { path: ^/pais, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/gradocientifico, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/ministerio, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/usuario, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/institucion, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/grupocientifico, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/clasificaciontipotesis, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/tipotesis, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/clasificaciontiposoftware, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/tiposoftware, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/grupoarticulo, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/tipoarticulo, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/tiponorma, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/tipopremio, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/tipoevento, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/autor/indexall, roles: ROLE_SUPERADMIN, requires_channel: https }
        #permisos del administrador institucional
        - { path: ^/area, roles: [ROLE_SUPERADMIN, ROLE_ADMIN], requires_channel: https }
        - { path: ^/organizador, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/editorial, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/revista, roles: ROLE_ADMIN, requires_channel: https }
        #permisos de directivos
        - { path: ^/autor/\d+/finddirectivosbyinstitucion, roles: ROLE_SUPERADMIN, requires_channel: https }
        - { path: ^/autor/new, roles: [ROLE_SUPERADMIN, ROLE_DIRECTIVO], requires_channel: https }
        - { path: ^/autor/\d+/delete, roles: [ROLE_SUPERADMIN, ROLE_ADMIN], requires_channel: https }
        - { path: ^/autor, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        #permisos de usuarios y directivos
        - { path: ^/balanceanual, roles: ROLE_GESTORBALANCE, requires_channel: https }
        #permisos de usuarios y directivos
        - { path: ^/notificacion, roles: [ROLE_DIRECTIVO, ROLE_ADMIN, ROLE_GESTORBALANCE, ROLE_USER], requires_channel: https }
        - { path: ^/mensaje, roles: [ROLE_DIRECTIVO, ROLE_ADMIN, ROLE_GESTORBALANCE, ROLE_USER], requires_channel: https }
        - { path: ^/premio, roles: ROLE_USER, requires_channel: https }
        - { path: ^/evento, roles: ROLE_USER, requires_channel: https }
        - { path: ^/tesis, roles: ROLE_USER, requires_channel: https }
        - { path: ^/software, roles: ROLE_USER, requires_channel: https }
        - { path: ^/patente, roles: ROLE_USER, requires_channel: https }
        - { path: ^/norma, roles: ROLE_USER, requires_channel: https }
        - { path: ^/monografia, roles: ROLE_USER, requires_channel: https }
        - { path: ^/libro, roles: ROLE_USER, requires_channel: https }
        - { path: ^/articulo, roles: ROLE_USER, requires_channel: https }
        - { path: ^/reporte, roles: ROLE_USER, requires_channel: https }
        #Funcionalidades de la API
        - { path: ^/api/requesttoken, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/*, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
