security:
    encoders:
        App\Entity\Autor: { algorithm: bcrypt , cost: 13 }
        App\Entity\Usuario: { algorithm: bcrypt , cost: 13 }

    role_hierarchy:
        ROLE_ADMIN:  ROLE_USER
        ROLE_DIRECTIVO:  ROLE_USER

    providers:
        chain_provider:
            chain:
                providers: [autores, usuarios]
        autores:
            entity: { class: App:Autor}
        usuarios:
            entity: { class: App:Usuario}


    firewalls:
        secured_area:
            pattern:    ^/*
            provider: chain_provider
            user_checker: App\Security\UserChecker
            form_login:
                login_path: index
                check_path: check
                default_target_path: index
                always_use_default_target_path: true
            logout:
                path:   logout
                target: index
                handlers: [app.logoutlistener]
            anonymous: ~
            remember_me:
                secret:  '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path: index

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pais, roles: ROLE_SUPERADMIN }
        - { path: ^/gradocientifico, roles: ROLE_SUPERADMIN }
        - { path: ^/ministerio/\d+/findbypais, roles: [ROLE_SUPERADMIN] }
        - { path: ^/ministerio, roles: ROLE_SUPERADMIN }
        - { path: ^/institucion/\d+/findbyministerio, roles: [ROLE_SUPERADMIN, ROLE_ADMIN] }
        #permisos del superadmin
        - { path: ^/usuario, roles: ROLE_SUPERADMIN }
        - { path: ^/institucion, roles: ROLE_SUPERADMIN }
        - { path: ^/area/\d+/findbyautor, roles: [ROLE_SUPERADMIN, ROLE_ADMIN, ROLE_DIRECTIVO] }
        - { path: ^/area, roles: [ROLE_SUPERADMIN, ROLE_ADMIN] }
        - { path: ^/grupocientifico, roles: ROLE_SUPERADMIN }
        - { path: ^/clasificaciontipotesis, roles: ROLE_SUPERADMIN }
        - { path: ^/tipotesis, roles: ROLE_SUPERADMIN }
        - { path: ^/clasificaciontiposoftware, roles: ROLE_SUPERADMIN }
        - { path: ^/tiposoftware, roles: ROLE_SUPERADMIN }
        - { path: ^/grupoarticulo, roles: ROLE_SUPERADMIN }
        - { path: ^/tipoarticulo, roles: ROLE_SUPERADMIN }
        - { path: ^/tiponorma, roles: ROLE_SUPERADMIN }
        - { path: ^/tipopremio, roles: ROLE_SUPERADMIN }
        - { path: ^/tipoencuentro, roles: ROLE_SUPERADMIN }
        - { path: ^/autor/indexall, roles: ROLE_SUPERADMIN }
        #permisos del administrador institucional
        - { path: ^/organizador, roles: ROLE_ADMIN }
        - { path: ^/editorial, roles: ROLE_ADMIN }
        - { path: ^/revista, roles: ROLE_ADMIN }
        #permisos de directivos
        - { path: ^/autor/\d+/index, roles: [ROLE_DIRECTIVO, ROLE_ADMIN] }
        - { path: ^/autor/\d+/finddirectivosbyinstitucion, roles: [ROLE_SUPERADMIN] }
        - { path: ^/autor/new, roles: [ROLE_SUPERADMIN, ROLE_DIRECTIVO, ROLE_ADMIN] }
        - { path: ^/autor/\d+/delete, roles: [ROLE_SUPERADMIN, ROLE_DIRECTIVO, ROLE_ADMIN] }
        - { path: ^/autor, roles: IS_AUTHENTICATED_FULLY }
        #permisos de usuarios y directivos
        - { path: ^/balanceanual, roles: ROLE_VISOR }
        #permisos de usuarios y directivos
        - { path: ^/notificacion, roles: [ROLE_DIRECTIVO, ROLE_ADMIN, ROLE_VISOR, ROLE_USER] }
        - { path: ^/mensaje, roles: [ROLE_DIRECTIVO, ROLE_ADMIN, ROLE_VISOR, ROLE_USER] }
        - { path: ^/premio, roles: ROLE_USER }
        - { path: ^/encuentro, roles: ROLE_USER }
        - { path: ^/tesis, roles: ROLE_USER }
        - { path: ^/software, roles: ROLE_USER }
        - { path: ^/patente, roles: ROLE_USER }
        - { path: ^/norma, roles: ROLE_USER }
        - { path: ^/monografia, roles: ROLE_USER }
        - { path: ^/libro, roles: ROLE_USER }
        - { path: ^/articulo, roles: ROLE_USER }
        - { path: ^/reporte, roles: ROLE_USER }
        - { path: ^/*, roles: IS_AUTHENTICATED_FULLY }
